Fix exception on initial property update
If `old_status` is initialized to a bool, the following causes the first
property update to fail:

Traceback (most recent call last):
File "/usr/bin/mpDris2", line 401, in timer_callback
    self._update_properties()
File "/usr/bin/mpDris2", line 597, in _update_properties
    if old_status['state'] != new_status['state']:
TypeError: 'bool' object has no attribute '__getitem__'